BoxLayoutExample:

<BoxLayoutExample>:
    orientation: 'vertical'
    Button:
        text: 'A'
        size: "100dp", "60dp"
        size_hint: None, None
    Button:
        text: 'B'
        size_hint: 1, 2
    Button:
        text: 'C'

<MainWidget>:
    Button:
        text: "Hello"
        size: "100dp", "80dp"
        pos: "100dp", "200dp"
        color: 0, 0, 1, 1
    Label:
        text: "Hello2"
        size: "100dp", "80dp"
        pos: "200dp", "300dp"
        color: 1, 0, 0, 1